apiVersion: jenkins.io/v1alpha2
kind: Jenkins
metadata:
  name: jenkins-demo-master
spec:
  master:
    basePlugins:
      - name: kubernetes
        version: "1.21.3"
      - name: workflow-job
        version: "2.36"
      - name: workflow-aggregator
        version: "2.6"
      - name: git
        version: "4.0.0"
      - name: job-dsl
        version: "1.76"
      - name: configuration-as-code
        version: "1.33"
      - name: configuration-as-code-support
        version: "1.19"
      - name: kubernetes-credentials-provider
        version: "0.13"
      - name: github
        version: 1.29.5
      - name: amazon-ecr
        version: "1.6"
      - name: docker-workflow
        version: "1.21"
      - name: blueocean
        version: "1.21.0"
      - name:  aws-credentials
        version: "1.28"
      - name : slack
        version: "2.34"
      - name: blueocean-display-url
        version: "2.3.0"
      - name: multibranch-action-triggers
        version: "1.5"
      - name: basic-branch-build-strategies
        version: "1.3.2"
    containers:
      - name: jenkins-master
        image: jenkins/jenkins:lts
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 12
          httpGet:
            path: /login
            port: http
            scheme: HTTP
          initialDelaySeconds: 80
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /login
            port: http
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 1500m
            memory: 3Gi
          requests:
            cpu: "1"
            memory: 500Mi
  seedJobs:
  - id: jenkins-operator
    targets: "jobs/*.jenkins"
    description: "Jenkins Operator repository"
# Add if repo required authentication see jenkins-github-sc.yaml
#    credentialType: usernamePassword
#    credentialID: jenkins-github
    repositoryBranch: master
    repositoryUrl: https://github.com/bbdsoftware/eks-jenkins-ci
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  labels:
  name: jenkins-demo-master
  resourceVersion: "57574"
spec:
  rules:
  - host: jenkins.YOURHOST
    http:
      paths:
      - backend:
          serviceName: jenkins-operator-http-jenkins-ql-master
          servicePort: 8080
        path: /blue